### PR TITLE
Change initial select value in Form class

### PR DESCRIPTION
**Pull request by lukejohnbrown**

### CODE REVIEW

**Review by ol1s — CHANGES_REQUESTED** [review]
@lukejohnbrown What do you think about either doing `strtolower($label)` or leave the `$label` out completely?

**Comment by lukejohnbrown** [comment]
Sure, maybe we just leave the $label out to avoid any issues!

**Comment by ol1s** [comment]
Great - can you amend the pull request and then I'll merge

**Comment by lukejohnbrown** [comment]
Change made!

**Review by ol1s — APPROVED** [review]

**Pull request merged**
